apiVersion: apps/v1
kind: Deployment
metadata:
  name: vagachat-api
spec:
  selector:
    matchLabels:
      app: vagachat-api
  replicas: 1
  template:
    metadata:
      labels:
        app: vagachat-api
    spec:
      containers:
        - name: vagachat-api
          image: vagabundocker/webchat
          # env:
          # - name: MY_VAR
          #   value: "roberto"
          resources:
            # requests:
            #   memory: "64Mi"
            #   cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 80
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vagachat-api-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: vagachat-api